config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :order_items
  get 'cart', to: 'cart#show' 
  get 'search', to: 'menu#search'
  resources :categories
  get 'menu', to: 'menu#index'
  devise_for :users
  resources :products
  root 'pages#home'
  get 'catering', to: 'pages#catering'
  get 'info', to: 'pages#info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal

    def subtotal
        order_items.collect {|order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0}.sum
    end

    private 

    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
      if persisted?
          self[:unit_price]
      else
          product.price
      end
  end

  def total
      return unit_price * quantity
  end

  private

  def set_unit_price
      self[:unit_price] = unit_price
  end

  def set_total
      self[:total] = total * quantity
  end
  
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :image
  has_many :order_items
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:heading, :body, :display)
  end
end

app/controllers/menu_controller.rb
# frozen_string_literal: true

class MenuController < ApplicationController
  before_action :set_cats
  def index
    @page = 'menu'
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def search
    query = params[:search]

    results = Product.where('name LIKE ?', "%#{query}%")
    if params[:filter] == 'Select Filter'
      @products = results
    else
      # 'Dairy Free'   -> 'dairy_free'   ->    :dairy_free
      symbol = params[:filter].gsub(/ /, '_').downcase!.to_sym

      @products = results.where(symbol => true)
    end
  end

  private

  def set_cats
    @cats = Category.all.where(display: true)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
    before_action :set_order
    
    def create
      @order_item = @order.order_items.new(order_params)
      @order.save
      session[:order_id] = @order.id
    end
  
    def update
      @order_item = @order.order_items.find(params[:id])
      @order_item.update_attributes(order_params)
      @order_items = current_order.order_items
    end
  
    def destroy
      @order_item = @order.order_items.find(params[:id])
      @order_item.destroy
      @order_items = current_order.order_items
    end
  
    private
    
    def order_params
      params.require(:order_item).permit(:product_id, :quantity)
    end
    
    def set_order
      @order = current_order
    end
  
  end
  

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    @page = 'home'
  end

  def catering
    @page = 'catering'
  end

  def info
    @page = 'info'
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :description, :price, :image, :category_id, :available, :catering,
                                    :featured)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
    def current_order
        if Order.find_by_id(session[:order_id]).nil?
            Order.new
        else
            Order.find_by_id(session[:order_id])
        end
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/menu_helper.rb
# frozen_string_literal: true

module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of $#{current_order.subtotal}", cart_path %>

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>
    <h3><%= item.product.name %></h3>
    <h3><%= item.product.price %></h3>
    <%= form_with model: item do |f| %>
        <%= f.hidden_field :product_id, value: item.product.id %>
        <%= f.number_field :quantity, value: item.quantity.to_i %>
        <%= f.submit "Update Cart" %>
        <%= link_to "Remove Items", item, method: :delete, remote: true %>
    <% end %>
    <h2>Subtotal: <%= item.total %></h2>
<% end %>
<h3>Your current order has a total of:  <%= current_order.subtotal %> </h3>

app/views/cart/show.html.erb
<div id="cart-item">
    <%= render 'cart_items' %>
</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :heading %>
    <%= f.input :body %>
    <%= f.input :display %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Heading</th>
      <th>Body</th>
      <th>Display</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.heading %></td>
        <td><%= category.body %></td>
        <td><%= category.display %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Heading:</strong>
  <%= @category.heading %>
</p>

<p>
  <strong>Body:</strong>
  <%= @category.body %>
</p>

<p>
  <strong>Display:</strong>
  <%= @category.display %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_alerts.html.erb
<% if notice %>
<div class="alert alert-primary alert-dismissible fade show" role="notice">
    <p class="notice"><%= notice %></p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% elsif alert %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <p class="alert"><%= alert %></p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<%#   in class to show allways%>
<nav class="navbar navbar-dark bg-dark mt-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
telefonos/wsp| direccion | redes twitter  instagram
    </a>
  </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
<%# fonto blando gris o negro con el logo %>
  <div class="container-fluid">
        <%= link_to root_path do %>
        <%= image_tag("/logo_wh.png", alt: 'Logo', width:"40",class: "navbar-brand")%>
        <% end %>
    <%= link_to 'Mangiare', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Menu", menu_path, class: "nav-link #{@page == 'menu' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
            <%= link_to "Catering", catering_path, class: "nav-link #{@page == 'catering' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
            <%= link_to "More Info", info_path, class: "nav-link #{@page == 'info' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
            <%= link_to "Customer Reviews", "", class: "nav-link #{@page == 'reviews' ? 'active' : ''}" %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark" aria-labelledby="navbarDropdown">
            <li class="nav-item">
              <%= link_to 'Edit Account', edit_user_registration_path, class: 'dropdown-item'  %>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item'  %>
            </li>
          </ul>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Create Account', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link'  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mangiare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
  </head>

  <body>
      <div class="col-12">
        <%= render 'layouts/navbar' %>
        <%= render 'layouts/alerts' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
  </body>

app/views/menu/_products.html.erb
<div class="container-fluid mb-5">
<div class="row">
    <% @cats.each do |cat| %>
        <%# <% if cat.products.where(featured: true).first.image.attached? %>
            <%# <%= image_tag(cat.products.where(featured: true).first.image, class:'img-fluid', id:'featured_img' )%> 
        <%# <% end %> 
        <div class="col-12 container bg-dark text-light">
            <h1 style= text-align:center> 
                <%= cat.heading %>
            </h1>
        </div>
        <% @products.each do |product| %>
            <% if product.category == cat %>
                <div class="col-4 container my-5 mx-auto" >
                    <div class="card">
                    <%= image_tag(product.image, class:'img-fluid', id:'featured_img' )%>
                    <div class="card-body">
                        <h4 class="card-title"><%= product.name %></h4>
                        <h5 class="card-description"><%= product.description %></h5>
                        <p class="card-text"><%= product.price %> <%= "| Available for catering" if product.catering %></p>
                        <%= form_with model: @order_item do |f| %>
                        <%= f.hidden_field :product_id, value: product.id %>
                        <%= f.number_field :quantity, value: 1, min: 1 %>
                        <%= f.submit "Add to cart" %>
                        <a href="#" class="btn btn-primary">Go somewhere</a>
                    </div>
                    </div>
                </div>
                    <% end %>
            <% end %> 

    <% end %>
    <% end %>
</div>



</div>

app/views/menu/_submenu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top pb-3">
<%# fonto blando gris o negro con el logo %>
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Promos", menu_path, class: "nav-link #{@page == 'menu' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
            <%= link_to "Combos", catering_path, class: "nav-link #{@page == 'catering' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
            <%= link_to "Entradas", info_path, class: "nav-link #{@page == 'info' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
            <%= link_to "Pizzas", "", class: "nav-link #{@page == 'reviews' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
            <%= link_to "Postres", "", class: "nav-link #{@page == 'reviews' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
            <%= link_to "Bebidas", "", class: "nav-link #{@page == 'reviews' ? 'active' : ''}" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/menu/index.html.erb
<div class="col-12">
<%= render 'menu/submenu' %>
<%= render 'menu/products' %>
</div>

app/views/menu/search.js.erb
$("#menu-products-container").html(" <%= j render 'menu/products' %> ");

app/views/order_items/create.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");

app/views/order_items/destroy.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/order_items/update.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/pages/catering.html.erb
<h1>Pages#catering</h1>
<p>Find me in app/views/pages/catering.html.erb</p>

app/views/pages/home.html.erb
<div class="container-fluid my-5 promo-container">
</div>


<div id="map" class="container-fluid">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3976.61749911938!2d-74.06530528552311!3d4.662097596613484!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e3f9a5990a8a8bb%3A0xc67ad6f767e9be98!2sCra.%2020b%20%2373-18%2C%20Bogot%C3%A1%2C%20Colombia!5e0!3m2!1sen!2sar!4v1619659705958!5m2!1sen!2sar" width="800px" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>

app/views/pages/info.html.erb
<div class="container-fluid col-4 my-5 mx-auto">
<div class="card mb-3">
  <img src="/eduardo.jpeg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Sobre nosotros</h5>
    <p>En MANGIARE Pizzería-Enoteca preparamos 
    pizzas artesanales neo napolitanas fermentadas 
    con masa madre y maduradas por 48 horas, las cuales 
    preparamos únicamente con mozzarella fior de latte, 
    todos nuestros productos se hacen con los mejores 
    ingredientes ya que todos son locales y los compramos 
    directamente a los productores para garantizar la mejor 
    calidad y apoyo al agro colombiano; también garantizamos 
    la calidad de nuestras carnes, todas criadas con técnicas 
    sostenibles y amigables con el medio ambiente. Somos un 
    restaurante hecho con corazón para ustedes!!</p>
  </div>
</div>

</div>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.file_field :image %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :available %>
    <%= f.input :catering %>
    <%= f.input :featured %>
    <%= f.collection_select(:category_id, Category.all, :id, :heading) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Available</th>
      <th>Catering</th>
      <th>Featured</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.available %></td>
        <td><%= product.catering %></td>
        <td><%= product.featured %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @product.available %>
</p>

<p>
  <strong>Catering:</strong>
  <%= @product.catering %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @product.featured %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>